# Generated by Django 5.0.6 on 2026-06-15 16:01

import django.db.models.deletion
import videos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Tên video')),
                ('file_id', models.CharField(blank=True, max_length=50, unique=True, verbose_name='File ID')),
                ('status', models.CharField(choices=[('pending', 'Chờ review'), ('reviewing', 'Đang review'), ('reviewed', 'Đã review'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('needs_revision', 'Cần sửa lại')], default='pending', max_length=30, verbose_name='Trạng thái')),
                ('current_version', models.PositiveIntegerField(default=1, verbose_name='Phiên bản hiện tại')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('thumb_gradient', models.CharField(default=videos.models.random_gradient, max_length=100, verbose_name='Gradient thumbnail')),
                ('category', models.CharField(choices=[('Tutorial', 'Tutorial'), ('Review', 'Review'), ('Comparison', 'Comparison'), ('Other', 'Khác')], default='Tutorial', max_length=50, verbose_name='Danh mục')),
                ('btv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL, verbose_name='BTV')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewing_videos', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'db_table': 'videos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm')),
                ('action', models.TextField(verbose_name='Hành động')),
                ('from_status', models.CharField(blank=True, max_length=30, null=True, verbose_name='Trạng thái trước')),
                ('to_status', models.CharField(blank=True, max_length=30, null=True, verbose_name='Trạng thái sau')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='videos.video', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Lịch sử duyệt',
                'verbose_name_plural': 'Lịch sử duyệt',
                'db_table': 'history_entries',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Nội dung')),
                ('timestamp', models.CharField(blank=True, max_length=10, verbose_name='Timestamp (mm:ss)')),
                ('resolved', models.BooleanField(default=False, verbose_name='Đã xử lý')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_comments', to='videos.video', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Số phiên bản')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên')),
                ('file', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='File video')),
                ('file_size', models.CharField(blank=True, default='—', max_length=50, verbose_name='Kích thước file')),
                ('duration', models.CharField(blank=True, default='—', max_length=20, verbose_name='Thời lượng')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_versions', to=settings.AUTH_USER_MODEL, verbose_name='Người tải lên')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='videos.video', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Phiên bản video',
                'verbose_name_plural': 'Phiên bản video',
                'db_table': 'video_versions',
                'ordering': ['number'],
                'unique_together': {('video', 'number')},
            },
        ),
    ]
