# Generated by Django 5.0.6 on 2026-06-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('Ency cam', 'Ency cam'), ('Ency robot', 'Ency robot'), ('Khách hàng tiêu biểu', 'Khách hàng tiêu biểu')], default='Ency cam', max_length=50, verbose_name='Danh mục'),
        ),
    ]
