# Generated by Django 5.0.6 on 2026-06-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_update_category_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('ENCY CAM', 'ENCY CAM'), ('ENCY ROBOT', 'ENCY ROBOT'), ('KHÁCH HÀNG TIÊU BIỂU', 'KHÁCH HÀNG TIÊU BIỂU')], default='ENCY CAM', max_length=50, verbose_name='Danh mục'),
        ),
    ]
