# Generated by Django 5.0.6 on 2026-06-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_update_category_uppercase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Timestamp (mm:ss)'),
        ),
    ]
