# Generated by Django 5.0.6 on 2026-06-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_comment_timestamp_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Timestamp (mm:ss)'),
        ),
    ]
