# Generated by Django 5.0.6 on 2026-06-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_comment_timestamp_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='YouTube URL'),
        ),
        migrations.AddField(
            model_name='video',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='YouTube Video ID'),
        ),
    ]
