# Generated by Django 5.0.6 on 2026-06-15 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm')),
                ('action', models.TextField(verbose_name='Hành động')),
                ('resource_type', models.CharField(choices=[('video', 'Video'), ('user', 'User'), ('system', 'System')], max_length=20, verbose_name='Loại tài nguyên')),
                ('resource_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID tài nguyên')),
                ('details', models.TextField(blank=True, verbose_name='Chi tiết')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
            ],
            options={
                'verbose_name': 'Audit log',
                'verbose_name_plural': 'Audit log',
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
